const GET_TOKEN = 'GET_TOKEN';
const ERASE_TOKEN = 'ERASE_TOKEN';
const CREATE_TOKEN = "CREATE_TOKEN";

const GET_LOGIN = 'GET_LOGIN';
const ERASE_LOGIN = 'ERASE_LOGIN';

export {GET_TOKEN, ERASE_TOKEN, CREATE_TOKEN, GET_LOGIN, ERASE_LOGIN}