const SAVE_LOGINPAGE_LOGIN = 'SAVE_LOGINPAGE_LOGIN';
const SAVE_LOGINPAGE_PASSWORD = 'SAVE_LOGINPAGE_PASSWORD';

const SAVE_REGISTERPAGE_LOGIN = 'SAVE_REGISTERPAGE_LOGIN';
const SAVE_REGISTERPAGE_PASSWORD = 'SAVE_REGISTERPAGE_PASSWORD';
const SAVE_REGISTERPAGE_PASSWORD_REPEAT = 'SAVE_REGISTERPAGE_PASSWORD_REPEAT';

const SAVE_MAINPAGE_PASSWORD_OLD = 'SAVE_MAINPAGE_PASSWORD_OLD';
const SAVE_MAINPAGE_PASSWORD_NEW = 'SAVE_MAINPAGE_PASSWORD_NEW';
const SAVE_MAINPAGE_PASSWORD_REPEAT = 'SAVE_MAINPAGE_PASSWORD_REPEAT';
const CLEAR_MAINPAGE_FORM = 'CLEAR_MAINPAGE_FORM';


export {
    SAVE_LOGINPAGE_LOGIN,
    SAVE_LOGINPAGE_PASSWORD,
    SAVE_REGISTERPAGE_LOGIN,
    SAVE_REGISTERPAGE_PASSWORD,
    SAVE_REGISTERPAGE_PASSWORD_REPEAT,
    SAVE_MAINPAGE_PASSWORD_OLD,
    SAVE_MAINPAGE_PASSWORD_NEW,
    SAVE_MAINPAGE_PASSWORD_REPEAT,
    CLEAR_MAINPAGE_FORM,
}